### ISSUE TITLE
health check посоветуйте для docker-compose

### ISSUE THREAD

**Issue by AlexBGoode** [YouROK/TorrServer#356]
Пускаю из предложенного docker-compose.yaml но иногда по логам все ок но сервер тупит и думается мне хорошо бы настроить healch check но не могу догадаться какую команду использовать чтобы тес был показательным

**Comment by TopperBG** [comment]
It can be some tool or internal command to check alive service e.g.
```
healthcheck:
      test: curl --fail http://localhost || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
```
