### ISSUE TITLE
[BUG] DLNA Doesn't work

### ISSUE THREAD

**Issue by Andrewkha** [YouROK/TorrServer#447]
**Describe the bug**
DLNA feature is enabled in TorrServer MatriX.133t features (running in official docker container), but DLNA is not visible over network 
**To Reproduce**
1. Go to Settigns - Additional - DLNA Media Server
2. Click on toggle button to enable DNLA, set a custom DLNA server name
3. See error - no error is observed, just DLNA media doesn't appear in the network

**Expected behavior**
I expect DLNA server to be available over network (worked previously)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: runing in a container station on QNAP NAS or on Ubuntu in docker container
 - TorrServer Version MatriX.133t

**Smartphone or tvbox on Android (please complete the following information):**
 - Device: [e.g. Ugoos am6]
 - OS: [e.g. Android 9]
 - TorrServer Version [e.g. MatriX.129]

**Additional context**

**Comment by ddonindia** [comment]
DLNA with docker needs host networking. Try passing --network=host in your docker run command

**Comment by Andrewkha** [comment]
@ddonindia thanks, this solved the original issue, but created another one - Torrserver web interface stopped working.
Here's my docker-compose.yaml

```
version: '3.3'
services:
    torrserver:
        image: ghcr.io/yourok/torrserver
        network_mode: "host"
        container_name: torrserver
        environment:
            - TS_PORT=5665
            - TS_DONTKILL=1
            - TS_HTTPAUTH=0
            - TS_CONF_PATH=/opt/ts/config
            - TS_TORR_DIR=/opt/ts/torrents
        volumes:
            - '/share/CACHEDEV1_DATA/Container/container-station-data/app_data/torrserver_data/CACHE:/opt/ts/torrents'
            - '/share/CACHEDEV1_DATA/Container/container-station-data/app_data/torrserver_data/CONFIG:/opt/ts/config'
        ports:
            - '8090:5665'
        restart: unless-stopped
```
