### ISSUE TITLE
running DLNA in docker

### ISSUE THREAD

**Issue by Lamardinho** [YouROK/TorrServer#449]
Hello everyone, please tell me what settings need to be added so that the DLNA server is visible on the my network?

```
version: '3.3'

services:

  torrserver:
    image: ghcr.io/yourok/torrserver
    container_name: torrserver
    environment:
      - TS_PORT=5665
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
    volumes:
      - torrserver_data:/opt/ts
      - './CACHE:/opt/ts/torrents'
      - './CONFIG:/opt/ts/config'
    ports:
      - '5665:5665'
      - '9081:9080'
    restart: unless-stopped

volumes:
  torrserver_data:
```

**Comment by Lamardinho** [comment]
I solved the problem myself, I had to write:
network_mode: "host"

Here is the correct file:

```
version: '3.3'

services:

  torrserver:
    image: ghcr.io/yourok/torrserver
    container_name: torrserver
    environment:
      - TS_PORT=5665
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
    volumes:
      - './CACHE:/opt/ts/torrents'
      - './CONFIG:/opt/ts/config'
    ports:
      - '5665:5665'
    restart: always
    network_mode: host
```
