### ISSUE TITLE
[BUG] WebUI breaks when host is proxied

### ISSUE THREAD

**Issue by dhvcc** [YouROK/TorrServer#485]
**Describe the bug**
When you proxy torrserver, to, for example, 0.0.0.0:80/torrserver - webui breaks, since the current logic for getting the host is broken and resolves itself to 0.0.0.0:80/

Bad commit https://github.com/YouROK/TorrServer/commit/7b2e1443f5e4953258e7ccdd713e23e6d3f37d7e
The previous logic, meaning a default of `''` is good since no matter the host, torrserver will request `{host_with_any_added_paths}/torrents`

I want to know why this commit was made (whether to fix some specific NAS vendor/cross platform issue or something) and if reverting it will break anything on other platforms, since it fixes the behavior on web

**To Reproduce**
**docker compose**
```yaml
services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - torrserver

  torrserver:
    image: ghcr.io/dhvcc/torrserver:latest
    restart: unless-stopped
    environment:
      - TS_PORT=5665
      - TS_DONTKILL=1
      - TS_HTTPAUTH=0
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
    expose:
      - '5665'
```

**nginx.conf**
```nginx
server {
    listen 80;
    server_name _;

    # TorrServer
    location /torrserver/ {
        proxy_pass http://torrserver:5665/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
} 
```

**Expected behavior**
I mean, it should resolve the path correctly, or better just use the '/' so that the browser resolves it itself

**Screenshots**
<img width="1508" alt="image" src="https://github.com/user-attachments/assets/0c78489b-edf3-459f-83c3-66e682ffc8b7" />

**Desktop (please complete the following information):**
 - OS: Docker
 - Docker latest
